#!/usr/bin/env sh
set -ef

# Build GoogleTest from source and install it
#
# See https://github.com/google/googletest/blob/d83fee138a9ae6cb7c03688a2d08d4043a39815d/googletest/README.md#build-with-cmake

gtest_version_tag=v1.14.0

temp_dir=$(mktemp -d)
cleanup()
{
    rm -rf -- "$temp_dir"
}
# NOTE: in Bash, `trap ... EXIT` would be enough (and recommended), but unfortunately we
# cannot change the shebang to `#!/usr/bin/env bash` because FreeBSD does not have Bash
# installed.
trap 'cleanup' INT TERM HUP EXIT

# Download
git clone --depth 1 -b "$gtest_version_tag" -- https://github.com/google/googletest.git "$temp_dir"
cd -- "$temp_dir"
mkdir build
cd build
# Configure - build only GoogleTest, not GoogleMock
cmake .. -DBUILD_GMOCK=OFF
# Build
make
# Install
if command -v sudo >/dev/null 2>&1; then
    sudo make install
else
    make install
fi
