#!/bin/sh -ef

if [ "$#" -eq 0 ]; then
	use_valgrind=
elif [ "$#" -eq 1 ] && [ "$1" = '--valgrind' ]; then
	use_valgrind=1
else
	echo "Usage: $0 [--valgrind]" >&2
	exit 1
fi

cd "$(dirname "$0")"/..

cd build/tests
if [ -n "$use_valgrind" ]; then
	valgrind -s --leak-check=full --show-leak-kinds=all ./unittest
else
	./unittest
fi
